common:
  provider: 'EDRLab'
  license:
    # Path to license schema
    schema: './schema/lcpl_schema.json'
  encryption:
    # Encryption XML XSD
    schema: './schema/encryption.xsd' 
  status:
    # statuc document schema
    schema: './schema/lsd_schema.json'
  crypto:
    # Path to LCP specific crypto package
    package: '/home/rbauzac/Readium/lcp-testing-tools-crypto/build/lcptests'
    cacert: './cert/cacert-edrlab-test.pem'

data:
  b1: 
    license: './data/b1.lcpl'
    passphrase: '2d30e2126f63b5e1f4b2c5cf042510656eba93ef97515e11'
  l1:
    license: './data/l1.lcpl'
    passphrase: 'e6cbceb6126d62a4058abb538eb17451e095559f97318eca'
  e1:
    epub: './data/e1.epub'
    passphrase: '750d93c6be98b5549c4c0603029d8ccc7f476944e7db4739'
  b2:
    license: './data/b2.lcpl'
    passphrase: '00b68ad18e8ee2fd801dcc9d3b0f6d736fa88143f199e0bf'
  b3:
    license: './data/b3.lcpl'
    passphrase: '885664aadb76124507b94ee519e33a4a3be97fe6b1a6119a'
  l2:
    license: './data/l2.lcpl'
    passphrase: 'e6cbceb6126d62a4058abb538eb17451e095559f97318eca'
