common:
  license:
    # Path to license schema
    schema: '/home/me/lcp-testing-tools/schema/lcpl_schema.json'
  crypto:
    # Path to LCP specific crypto package
    package: '/home/me/lcp-testing-tools-crypto/build/lcptests'
    cacert: '/home/me/certs/cacert.pem'


test1.1:
  license: '/home/me/licenses/b1.lcpl'
  passphrase: 'test_passphrase'
