common:
  provider: 'EDRLab'
  license:
    # Path to license schema
    schema: './schema/lcpl_schema.json'
  encryption:
    # Encryption XML XSD
    schema: './schema/encryption.xsd' 
  status:
    # statuc document schema
    schema: './schema/lsd_schema.json'
  crypto:
    # Path to LCP specific crypto package
    package: '/home/rbauzac/Readium/lcp-testing-tools-crypto/build/lcptests'
    cacert: './cert/cacert-edrlab-test.pem'

data:
  b1: 
    license: './data/b1.lcpl'
    passphrase: 'b127b2f49135789d7aea5ff3946e328c2de0eb58f72bebe6'
  l1:
    license: './data/l1.lcpl'
    passphrase: 'ddeec0900a8acdd66fd54e6af68b21bb959ddb16b04ccf0e'
  e1:
    epub: './data/e1.epub'
    passphrase: '0fe170e31a10291ef2fd3c673fe3eb2863eda83bd051a318'
  b2:
    license: './data/b2.lcpl'
    passphrase: '09659376263329f2bb3b121d56139655c87fe46a5febfcd5'
  b3:
    license: './data/b3.lcpl'
    passphrase: 'a13b599bccddd083876c1a9e88d8193fdd1f25a7d3c73c53'
  l2:
    license: './data/l2.lcpl'
    passphrase: 'ddeec0900a8acdd66fd54e6af68b21bb959ddb16b04ccf0e'
